#!/bin/bash
echo "IP DNS: 200.229.248.10"
echo "PORTA DNS: 37925"
echo "IP web www.exemplo.psi.br: 203.0.113.200"
echo "PORTA web www.exemplo.psi.br: 80"

sudo tcpdump -i any -w /tmp/capturaVictorCeschini.pcap -c 4200

ping -c 10 192.0.2.160
ping -c 10 192.0.2.100
ping -c 10 200.229.248.10
ping -c 10 203.0.113.200

wget http://www.exemplo.psi.br